### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by Oyebolade** [justlaunchit/fractional-app#14]
### Introduction to WordPress
- [ ] Getting Started with WordPress
- [ ] How to make a website with Astra

**Comment by Oyebolade** [comment]
Sir, @deletosh After downloading the local setup, I was able to installed it, but when I wanted to login to admin dashboard it redirected me back to login page. And I've tried to re-installed it. It is still the same thing.

![wordpress](https://github.com/justlaunchit/fractional-app/assets/57053389/6454e23b-5907-4039-92a8-f72eaac05add)

And it's not that the password is not correct. 
Thanks

**Comment by deletosh** [comment]
Did you try creating a new Wordpress instance?

**Comment by deletosh** [comment]
@Oyebolade did you try deleting that old instance and trying a new one?

**Comment by Oyebolade** [comment]
Yes, I've deleted the new site I created severally and created new one. It is all the the same.
I've also cleared the browser cache.
I've try almost everything I read online.

I don't know if I should delete the setup itself and download another one.

**Comment by Oyebolade** [comment]
It has worked
I uninstalled it and downloaded the previous version to the latest one

**Comment by Oyebolade** [comment]
@deletosh 
I have finished the Astra Tutorial, but the version of the video Tutorial is different from the recent version.

After customizing the footer, I was unable to align the about column with the connect column
![mylogofooter](https://github.com/justlaunchit/fractional-app/assets/57053389/b0472118-7ac4-4a05-a460-95d27c3c4e71)

**Comment by Oyebolade** [comment]
The issue has been solved
Thanks

**Comment by deletosh** [comment]
@Oyebolade this is very, very nice 👏🏿👏🏿

How are you feeling?

**Comment by Oyebolade** [comment]
I'm happy
I later realized that the footer is like the hug in figma auto layout. When you remove one content, it will adjust itself to fit in.

**Comment by Victorkayz** [comment]
"I have finished the Astra Tutorial, but the version of the video Tutorial is different from the recent version.
 After customizing the footer, I was unable to align the about column with the connect column "
@Oyebolade like you rightly observed, the version of the tutorial is different from what we are using right now, but my question is that were you able to edit the footer in the Elementor or you had to use the CUSTOMIZE? The tutor used  Elementor for the  footer but had to use customize for the header.  I seem to not know how to edit the footer using Elementor

**Comment by deletosh** [comment]
@Victorkayz there's a fairly new way to do this: https://wpastra.com/docs/create-footer-with-footer-builder/
