### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by Victorkayz** [justlaunchit/fractional-app#17]
Learn how to use WordPress
- [x] [Watch this first](https://www.youtube.com/watch?v=fArmNhkSrSw&pp=ygUVbG9jYWwgd29yZHByZXNzIGd1aWRl)
- [x] [How to Make a Website with Astra](https://www.youtube.com/watch?v=HSIb_VCS1Dc)

**Comment by Victorkayz** [comment]
@deletosh @Oyebolade when i choose a template on ASTRA theme starter template and i decided to work with that template, it doesn't show where i can import the template and use ELEMENTOR to start tweaking and edit the site, and instead it takes me to where i can publish the site and i think i have mistakenly publish a site....What can i do different!

**Comment by Victorkayz** [comment]
Thanks, i think i found my way around it

**Comment by Oyebolade** [comment]
> Thanks, i think i found my way around it

So sorry for the late response

I'm happy you've gotten a solution to the problem

**Comment by Victorkayz** [comment]
I'm done with this, but reference needed from time to time!
