### ISSUE TITLE
Fluent

### ISSUE THREAD

**Issue by Oyebolade** [justlaunchit/fractional-app#19]
Creating a contact form using Fluent Forms

**Comment by Oyebolade** [comment]
@deletosh 
Is the Fluent forms a plugin? 
Also, how do we install it on WordPress?

**Comment by Oyebolade** [comment]
Done with Fluent (Plugin installed and activated)
Interesting!

**Comment by Oyebolade** [comment]
Done with Fluent (Plugin installed and activated)
Interesting!

**Comment by deletosh** [comment]
@Oyebolade what did you find interesting about it?

**Comment by Oyebolade** [comment]
It is easy to use and understand.
Also stress free, fast and fluent just has the name given to it. What you just need is to be dragging any form field you want.
