### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by Oyebolade** [justlaunchit/fractional-app#20]
### Getting Started with JavaScript
 - [x] [An Introduction](https://javascript.info/getting-started)
      - [x] [An Introduction to JavaScript](https://javascript.info/intro)
      - [x] [Manuals and specifications](https://javascript.info/manuals-specifications)
      - [x] [Code editors](https://javascript.info/code-editors)
      - [x] [Developer console](https://javascript.info/devtools)
- [x] [JavaScript Fundamentals](https://javascript.info/first-steps)
  - [x] [Hello, world!](https://javascript.info/hello-world)
  - [x] [Code structure](https://javascript.info/structure)
  - [x] [The modern mode, "use strict"](https://javascript.info/strict-mode)
  - [x] [Variables](https://javascript.info/variables)
  - [x] [Data types](https://javascript.info/types)
  - [x] [Interaction: alert, prompt, confirm](https://javascript.info/alert-prompt-confirm)
  - [x] [Type Conversions](https://javascript.info/type-conversions)
  - [x] [Basic operators, maths](https://javascript.info/operators)
  - [x] [Comparisons](https://javascript.info/comparison)
  - [x] [Conditional branching: if, '?'](https://javascript.info/ifelse)
  - [x] [Logical operators](https://javascript.info/logical-operators)
  - [x] [Nullish coalescing operator '??'](https://javascript.info/nullish-coalescing-operator)
  - [x] [Loops: while and for](https://javascript.info/while-for)
  - [x] [The "switch" statement](https://javascript.info/switch)
  - [x] [Functions](https://javascript.info/function-basics)
  - [x] [Function expressions](https://javascript.info/function-expressions)
  - [x] [Arrow functions, the basics](https://javascript.info/arrow-functions-basics)
  - [x] [JavaScript specials](https://javascript.info/javascript-specials)

- [x] [Data types](https://javascript.info/data-types)
  - [x] [Methods of primitives](https://javascript.info/primitives-methods)
  - [x] [Numbers](https://javascript.info/number)
  - [x] [Strings](https://javascript.info/string)
  - [x] [Arrays](https://javascript.info/array)
  - [x] [Array methods](https://javascript.info/array-methods)
  - [x] [Iterables](https://javascript.info/iterable)
  - [x] [Map and Set](https://javascript.info/map-set)
  - [x] [WeakMap and WeakSet](https://javascript.info/weakmap-weakset)
  - [x] [Object.keys, values, entries](https://javascript.info/keys-values-entries)
  - [x] [Destructuring assignment](https://javascript.info/destructuring-assignment)
  - [x] [Date and time](https://javascript.info/date)
  - [x] [JSON methods, toJSON](https://javascript.info/json)

**Comment by Oyebolade** [comment]
Discovered new framework like CoffeeScript and Brython

**Comment by dmystical-coder** [comment]
Are you using [Javascript Info](https://javascript.info)?

**Comment by Oyebolade** [comment]
The link I followed is on the milestone 1

**Comment by Oyebolade** [comment]
Done with JavaScript
