### ISSUE TITLE
Pabbly

### ISSUE THREAD

**Issue by Oyebolade** [justlaunchit/fractional-app#21]
Connect WordPress to Pabbly

**Comment by Oyebolade** [comment]
Done watching the video

**Comment by Oyebolade** [comment]
I notice coping WordPress URL to Pabbly only works for online WordPress and not offline
@deletosh

**Comment by deletosh** [comment]
@Oyebolade it can, are you still using WP from Local?

**Comment by Oyebolade** [comment]
Yes, I'm still using WordPress from local
