### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by DorcasOpatola** [justlaunchit/fractional-app#24]
- [x] Watch this first

- [x] How to Make a Website with Astra

**Comment by DorcasOpatola** [comment]
I need some help, I can't sign in to WordPress. @deletosh 

I'm working on the first video in this task. I am unable to get past the instruction at 4:06.
I've created an account with local, downloaded it to my laptop, created the site and everything. 
As shown in the screenshot where I am to enter my login details, every time I put in my details it just reloads the sign-in page again. I don't know what else to do.

I clicked the forgot password button, said they've sent me a mail. There's nothing in my email nor spam.

Is there a special process to this that I'm missing?
![image](https://github.com/justlaunchit/fractional-app/assets/66256070/3a3d9238-3d3f-4890-8dff-64e479c8e3cb)

**Comment by deletosh** [comment]
@DorcasOpatola  try this to reset the password with what you installed via Local. Click here: https://localwp.com/help-docs/troubleshooting/reset-a-local-sites-wordpress-admin-password/

**Comment by DorcasOpatola** [comment]
Thank you for responding quickly. It doesn't work, same issue still happening.

**Comment by deletosh** [comment]
@DorcasOpatola delete that wordpress install and try another one.

**Comment by DorcasOpatola** [comment]
I am going through the posts on the community forum. The problem is a well-discussed bug feature of the current release.
I'm trying to make sense of it but, if I can't in an hour's time I'll download another one.

**Comment by DorcasOpatola** [comment]
I found the solution finally! It works now, thank you.
![image](https://github.com/justlaunchit/fractional-app/assets/66256070/f2bab7b1-d2b0-44ec-a9c6-74ec8fefdd0b)

**Comment by deletosh** [comment]
@DorcasOpatola great!

**Comment by DorcasOpatola** [comment]
earth.local

**Comment by DorcasOpatola** [comment]
Completed!

**Comment by deletosh** [comment]
@DorcasOpatola can you share the sample?

**Comment by DorcasOpatola** [comment]
Do you mean as a screenshot? I did not purchase hosting for the website, so I do not know how to share it.
Also, the website is based on a personal portfolio, I am creating another one for the fractional app.
