### ISSUE TITLE
Pabbly

### ISSUE THREAD

**Issue by Victorkayz** [justlaunchit/fractional-app#25]
- [x] [Connect WordPress to Pabbly](https://www.youtube.com/watch?v=2p8KCakiUOI)

**Comment by Victorkayz** [comment]
@deletosh @Oyebolade Just to clear my doubt! Does pabbly connect works with Local server because i was trying to automate my wordpress , it keeps saying "Base url is Invalid"

**Comment by Victorkayz** [comment]
Still need to learn and practice how to use Pabbly connect for automation but i'm done with this video for now

**Comment by deletosh** [comment]
@Victorkayz using Pabbly comes with practice, just using the Google Sheet sample to see how it works should be OK for now.
